// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mtntrlbuhcbdrngiubdu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10bnRybGJ1aGNiZHJuZ2l1YmR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI4MTQ3MzIsImV4cCI6MjA4ODM5MDczMn0.-GRBZbawCT5kU-CnQCt09LgIbB046ZsqQPA1zN41PaQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});